npmAlwaysAuth: true
npmRegistryServer: "https://artifactory.adesso-financial.de/artifactory/api/npm/dws-npm-combined"
yarnPath: .yarn/releases/yarn-3.5.1.cjs
npmAuthIdent: team_dws_sfmc:3uMQyWog7pdbH4VhCI6Q